name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

env:
  BUILD_TYPE: Release

jobs:
  format-check:
    name: Format check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++ programs
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: '14'
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        c_compiler: [gcc, clang, cl]
        build_shared: [true, false]
        build_type: [Debug, Release]
        include:
          - c_compiler: gcc
            cpp_compiler: g++
          - c_compiler: clang
            cpp_compiler: clang++
          - c_compiler: cl
            cpp_compiler: cl
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang
          - os: macos-latest
            c_compiler: cl
          - os: macos-latest
            c_compiler: gcc
          - os: ubuntu-latest
            c_compiler: cl
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        env:
          SANITIZE: ${{ matrix.build_type == 'Debug' && matrix.os == 'ubuntu-latest' && matrix.c_compiler == 'clang' && 'ON' || 'OFF' }}
        run: >
          cmake -B ${{github.workspace}}/build
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}}
          -DCMAKE_C_COMPILER=${{matrix.c_compiler}}
          -DCMAKE_CXX_COMPILER=${{matrix.cpp_compiler}}
          -DTT_BUILD_TESTS=ON
          -DBUILD_SHARED_LIBS=${{matrix.build_shared}}
          -DTT_SANITIZE=${{env.SANITIZE}}
      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}
      - name: Test
        run: ctest --test-dir ${{github.workspace}}/build -C ${{matrix.build_type}} --output-on-failure
