name: docs

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install doxygen
        run: |
          sudo apt update
          sudo apt install doxygen
      - name: Install Python build dependencies
        run: |
          pip install sphinx breathe myst-parser sphinx-book-theme          
      - name: Configure
        run: >
          cmake -B ${{github.workspace}}/build -DTT_BUILD_DOCS=ON
      - name: Build
        run: cmake --build ${{github.workspace}}/build --target docs
      - name: Package artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{github.workspace}}/build/docs/docs/sphinx
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
