name: Create release

on:
  push:
    branches: ["release-test"]

jobs:
  release:
    name: Tag and create a new release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate tag
        run: echo "TAG=$(date -u +%Y-W%W)" >> $GITHUB_ENV
      - run: 'echo "TAG: $TAG"'
      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create $TAG --generate-notes -p --latest
          
          
  

  
