name: Create release

on:
  push:
    branches: ["release-test"]

jobs:
  release:
    name: Tag and create a new release
    runs-on: ubuntu-latest
    steps:
      - name: Generate tag
        run: echo "TAG=$(date -u +%Y-W%W)" >> $GITHUB_ENV
      - run: 'echo "TAG: $TAG"'
          
  

  
